(defparameter *previous* '(0 0))
(defparameter *x* 0)
(defparameter *i* 0)

(defun fibonacci (times)
	(init)
	(dotimes (*i* times) 
		(if (zerop *i*) (setq *x* 1) (setq *x* (+ (car *previous*) (cadr *previous*))))
		(setf *previous* (cons (cadr *previous*) (cons *x* ())))
		(print *x*)	
	)
)

(defun init ()
	(setq *x* 0)
	(setq *i* 0)
	(setq *previous* '(0 0))
)